import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { AppModule } from '../../src/app.module';

/**
 * ============================================================================
 * KATA 05 — QUEUES & JOBS  (Week 5)   — offload + retry/backoff + dead-letter
 * ============================================================================
 * These tests are RED on a fresh `kata-05-queues-jobs` branch. There is no
 * /jobs route yet. Your assignment is to stand up a BullMQ queue + worker and
 * expose three endpoints so that work is done OUT-OF-BAND from the request:
 * the HTTP handler only ENQUEUES, a separate worker PROCESSES, failures RETRY
 * with backoff, and a job that exhausts its retries lands in a dead-letter
 * list instead of vanishing. Do NOT edit this file — the spec is the contract.
 *
 * Run just this kata:
 *   npm run test:kata -- test/katas/kata-05-queues-jobs.e2e-spec.ts
 *
 * ---------------------------------------------------------------------------
 * WHAT BULLMQ IS (so the moving parts below make sense)
 * ---------------------------------------------------------------------------
 * A BullMQ `Queue` is a PRODUCER: `queue.add(name, data, opts)` writes a job
 * into Redis and returns immediately. A BullMQ `Worker` is a CONSUMER running
 * in a separate loop: it BRPOP-style pulls jobs out of Redis and runs your
 * processor `async (job) => {...}`. Producer and consumer share nothing but
 * Redis — that decoupling is the whole point. `attempts`/`backoff` job options
 * make the worker re-run a throwing job; when attempts are used up the job is
 * moved to the "failed" set (and you forward it to your own dead-letter list).
 *
 * Spring/JPA parallel: this is what `@Async` + `@Retryable` hide from you. The
 * annotation quietly hands the method to a `TaskExecutor` thread pool and, on a
 * plain `@Async`, a crash BEFORE the pool drains loses the work — there is no
 * Redis-backed record. Wiring the Queue and Worker by hand here is how you see
 * what "durable, retried, at-least-once" actually costs.
 * Docs: https://docs.bullmq.io/guide/jobs  and  .../guide/retrying-failing-jobs
 *
 * ---------------------------------------------------------------------------
 * CONTRACT
 * ---------------------------------------------------------------------------
 * POST /jobs
 *   body: { "failTimes"?: number, "workMs"?: number }
 *     failTimes  how many of the FIRST runs of this job must throw before it is
 *                allowed to succeed (default 0 = succeed on the first run).
 *     workMs     how long the processor should "work" (sleep) once it decides to
 *                succeed (default 0). Used to prove the HTTP call did not block
 *                on the work.
 *   -> 202 { jobId: string }
 *      The handler ONLY enqueues. It MUST return before the job is processed.
 *
 * GET /jobs/:jobId
 *   -> 200 { jobId: string, state: string, runs: number }
 *      state  the BullMQ job state: "waiting" | "active" | "completed" |
 *             "failed" | "delayed" (via job.getState()); "unknown" if the id is
 *             not found.
 *      runs   how many times your PROCESSOR BODY has actually executed for this
 *             job (a counter you increment at the top of the processor, e.g. in
 *             Redis keyed by jobId — the queue's own `attemptsMade` is BullMQ's
 *             bookkeeping; `runs` is YOUR proof the work ran). A retried job
 *             runs more than once; a dead-lettered job ran exactly `attempts`
 *             times.
 *
 * GET /jobs/dead-letter
 *   -> 200 { jobIds: string[] }
 *      Job ids that exhausted every retry and were moved to your dead-letter
 *      list. A job that fails MORE than its retry budget must appear here — the
 *      failure mode this kata defends against is "the job just disappeared".
 *
 * REQUIRED QUEUE CONFIG (part of the contract):
 *   attempts = 3  (i.e. 1 initial try + 2 retries) with a SHORT backoff so the
 *   tests finish in time. A job with failTimes < 3 must eventually succeed; a
 *   job with failTimes >= 3 must exhaust its attempts and be dead-lettered.
 * ============================================================================
 */
describe('Kata 05 — Queues & jobs (e2e)', () => {
  let app: INestApplication;

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();
    app = moduleRef.createNestApplication();
    await app.init();
  });

  afterAll(async () => {
    // Your JobsModule MUST close its Worker and Queue on shutdown, or Jest hangs
    // on open Redis handles. (Spring parallel: the container calling
    // ExecutorService.shutdown() for you.)
    await app?.close();
  });

  /** Poll GET /jobs/:jobId until `state` is terminal, or time out. */
  const waitForState = async (
    jobId: string,
    terminal: string[],
    timeoutMs = 15000,
  ): Promise<{ state: string; runs: number }> => {
    const deadline = Date.now() + timeoutMs;
    let last = { state: 'unknown', runs: 0 };
    while (Date.now() < deadline) {
      const res = await request(app.getHttpServer()).get(`/jobs/${jobId}`);
      if (res.status === 200) {
        last = { state: res.body.state, runs: res.body.runs };
        if (terminal.includes(last.state)) return last;
      }
      await new Promise((r) => setTimeout(r, 100));
    }
    return last;
  };

  it(
    'OFFLOADS the work: POST returns 202 immediately, the worker finishes it later',
    async () => {
      // The processor "works" for 800ms. If the HTTP handler did the work inline
      // instead of enqueuing, this POST could not come back in a fraction of that.
      const t0 = Date.now();
      const enqueued = await request(app.getHttpServer())
        .post('/jobs')
        .send({ workMs: 800 })
        .expect(202);
      const elapsed = Date.now() - t0;

      const jobId = enqueued.body.jobId;
      expect(typeof jobId).toBe('string');
      expect(jobId.length).toBeGreaterThan(0);
      // enqueue-and-return, not run-inline
      expect(elapsed).toBeLessThan(500);

      // at return time the slow job cannot possibly be done yet
      const immediate = await request(app.getHttpServer())
        .get(`/jobs/${jobId}`)
        .expect(200);
      expect(immediate.body.state).not.toBe('completed');

      // ...but the worker does pick it up and complete it
      const final = await waitForState(jobId, ['completed', 'failed']);
      expect(final.state).toBe('completed');
      expect(final.runs).toBe(1);
    },
    20000,
  );

  it(
    'RETRIES a transient failure with backoff, then succeeds',
    async () => {
      // fails its first 2 runs, succeeds on the 3rd — within the attempts budget
      const enqueued = await request(app.getHttpServer())
        .post('/jobs')
        .send({ failTimes: 2 })
        .expect(202);
      const jobId = enqueued.body.jobId;

      const final = await waitForState(jobId, ['completed', 'failed']);
      expect(final.state).toBe('completed');
      // it did not give up on the first throw: the processor body ran 3 times
      expect(final.runs).toBe(3);
    },
    20000,
  );

  it(
    'DEAD-LETTERS a job that exhausts its retries — it is NOT silently lost',
    async () => {
      // fails more times than the attempts budget allows, so it can never succeed
      const enqueued = await request(app.getHttpServer())
        .post('/jobs')
        .send({ failTimes: 99 })
        .expect(202);
      const jobId = enqueued.body.jobId;

      const final = await waitForState(jobId, ['completed', 'failed']);
      expect(final.state).toBe('failed');
      // it burned exactly its whole attempts budget before being parked (3 runs)
      expect(final.runs).toBe(3);

      // and it landed in the dead-letter list rather than disappearing
      const dlq = await request(app.getHttpServer())
        .get('/jobs/dead-letter')
        .expect(200);
      expect(Array.isArray(dlq.body.jobIds)).toBe(true);
      expect(dlq.body.jobIds).toContain(jobId);
    },
    20000,
  );
});
