import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { DataSource } from 'typeorm';
import { AppModule } from '../../src/app.module';
import { Account } from '../../src/accounts/account.entity';

/**
 * ============================================================================
 * KATA 03b — LOCK ORDERING / DEADLOCK  (extension of Week 3)
 * ============================================================================
 * This is an EXTRA test on top of the graded kata-03 spec — not part of the
 * original contract. It defends against a DEADLOCK your A->B-only test can never
 * trigger. Do NOT edit this file — the spec is the contract.
 *
 * Run just this test:
 *   npm run test:kata -- test/katas/kata-03b-lock-ordering.e2e-spec.ts
 *
 * The failure mode:
 *   Your transfer locks the SOURCE row, then the DESTINATION row (`from` then
 *   `to`). Fire A->B and B->A at the same instant and the two transactions grab
 *   the SAME two rows in OPPOSITE order:
 *
 *       Req A->B :  lock A ✔ ... then wants B ⏳
 *       Req B->A :  lock B ✔ ... then wants A ⏳
 *       -> each holds what the other needs -> Postgres kills one (40P01)
 *
 *   Money is still conserved (the victim rolls back cleanly), so the kata-03
 *   conservation check CANNOT see this bug. What exposes it is the deadlock
 *   itself: a transfer that had enough funds still fails. This test seeds both
 *   accounts richly so NO transfer can legitimately hit 409 — every request
 *   MUST end 200/201. Any non-2xx here is a deadlock victim (your current
 *   `catch` masks 40P01 as a 400) and the test goes RED.
 *
 * The fix (your src/ work — do not ask me to write it):
 *   Acquire the two row locks in a DIRECTION-INDEPENDENT order. Sort the two
 *   ids and always lock the smaller one first, so A->B and B->A both grab A
 *   before B. Same rows, same order, no cycle. (You can lock both in one
 *   `WHERE id IN (:a,:b) ORDER BY id FOR UPDATE`, or two locked reads issued in
 *   sorted order — then still debit `from` / credit `to` as before.)
 *
 * Spring/JPA parallel: identical hazard with `@Lock(PESSIMISTIC_WRITE)` /
 * `SELECT ... FOR UPDATE` under @Transactional. The textbook cure is the same —
 * impose a global lock ordering on the resources.
 *
 * NOTE: deadlocks are probabilistic. This runs several high-contention rounds so
 * that an unordered implementation is overwhelmingly likely to hit one; a
 * correctly ordered implementation passes every round every time.
 * ============================================================================
 */
describe('Kata 03b — lock ordering / deadlock (e2e)', () => {
  let app: INestApplication;
  let dataSource: DataSource;
  let base: string;

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();
    app = moduleRef.createNestApplication();
    await app.listen(0);
    dataSource = app.get(DataSource);
    base = (await app.getUrl()).replace('[::1]', '127.0.0.1');
    // Warm the pool so the burst races on already-open connections — a cold pool
    // serializes the first requests and can hide the deadlock.
    await Promise.all(
      Array.from({ length: 30 }, () => request(base).get('/health')),
    );
  });

  afterAll(async () => {
    await app?.close();
  });

  const seedAccount = async (balanceCents: number): Promise<string> => {
    const repo = dataSource.getRepository(Account);
    const saved = await repo.save(
      repo.create({
        name: `kata03b-${Date.now()}-${Math.random()}`,
        balanceCents,
      }),
    );
    return saved.id;
  };

  const balanceOf = async (id: string): Promise<number> => {
    const a = await dataSource.getRepository(Account).findOneBy({ id });
    return a!.balanceCents;
  };

  it(
    'survives bidirectional transfers with no deadlock — every well-funded transfer succeeds',
    async () => {
      const perDirection = 20;
      const amount = 100;

      for (let round = 0; round < 4; round++) {
        // Seed both accounts so richly that NO transfer can ever hit 409 for
        // insufficient funds. Then the ONLY reason a transfer can fail is a
        // deadlock — which is exactly what we are hunting.
        const a = await seedAccount(1_000_000);
        const b = await seedAccount(1_000_000);

        const aToB = Array.from({ length: perDirection }, () =>
          request(base)
            .post(`/accounts/${a}/transfer`)
            .send({ toAccountId: b, amountCents: amount }),
        );
        const bToA = Array.from({ length: perDirection }, () =>
          request(base)
            .post(`/accounts/${b}/transfer`)
            .send({ toAccountId: a, amountCents: amount }),
        );

        // Interleave the two directions so opposing lock orders collide.
        const calls: Promise<request.Response>[] = [];
        for (let i = 0; i < perDirection; i++) {
          calls.push(aToB[i], bToA[i]);
        }
        const responses = await Promise.all(calls);

        const ok = responses.filter(
          (r) => r.status === 200 || r.status === 201,
        );
        const bad = responses.filter(
          (r) => r.status !== 200 && r.status !== 201,
        );

        // No transfer had any legitimate reason to fail. A non-2xx here is a
        // deadlock victim -> your lock order depends on transfer direction.
        expect(bad.map((r) => r.status)).toEqual([]);
        expect(ok.length).toBe(perDirection * 2);

        // Sanity: equal transfers both ways -> balances return to the start,
        // money conserved.
        expect((await balanceOf(a)) + (await balanceOf(b))).toBe(2_000_000);
      }
    },
    30000,
  );
});
