import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import Redis from 'ioredis';
import { AppModule } from '../../src/app.module';
import { REDIS } from '../../src/redis/redis.module';

/**
 * ============================================================================
 * KATA 04 — CACHING  (Week 4)   — cache-aside + invalidation + stampede
 * ============================================================================
 * These tests are RED on a fresh `kata-04-caching` branch. Today `GET
 * /products/:id` reads straight from Postgres every time and returns the raw
 * entity. Your assignment is to put a Redis cache in front of that read using
 * the **cache-aside** (lazy-loading) pattern, invalidate it on write, and make
 * it survive a concurrent cold-cache stampede. Do NOT edit this file — the
 * spec is the contract.
 *
 * Run just this kata:
 *   npm run test:kata -- test/katas/kata-04-caching.e2e-spec.ts
 *
 * ---------------------------------------------------------------------------
 * CONTRACT
 * ---------------------------------------------------------------------------
 * GET /products/:id
 *   -> 200 { id, name, priceCents, stock, version, source }
 *      `source` is "db"    when this response was served from Postgres (and the
 *                          value was (re)written into Redis as a side effect),
 *      `source` is "cache" when this response was served from Redis.
 *   A cold read is a MISS (source:"db") and populates the cache.
 *   An immediately-following read is a HIT (source:"cache") with identical data.
 *
 * POST /products/:id/purchase   (already exists — it mutates stock)
 *   After a successful purchase the cached copy is STALE and MUST be
 *   invalidated: the next GET reflects the new stock and is a fresh read
 *   (source:"db"). A write that leaves a stale cache entry behind is the bug.
 *
 * GET /products/:id/db-reads
 *   -> 200 { dbReads: <int> }   diagnostic: how many times the service has
 *      actually gone to Postgres for THIS id since the process started. This is
 *      your load gauge — the whole point of the cache is to keep this number
 *      low. Increment it exactly where you query the DB for a single product.
 *
 * ---------------------------------------------------------------------------
 * THE NASTY CASE — cache stampede (a.k.a. dog-piling / thundering herd)
 * ---------------------------------------------------------------------------
 * When a hot key is cold (first ever read, or just invalidated/expired), N
 * concurrent requests ALL miss at the same instant and ALL run the expensive
 * DB read before anyone populates the cache. Naive cache-aside turns 1 slow
 * query into N slow queries precisely when you are busiest. The fix is
 * single-flight: only the FIRST miss touches the DB; the rest wait for it and
 * then read the freshly-cached value. The assertion below pins `dbReads` to
 * exactly 1 across a burst of concurrent cold reads.
 *
 * Spring/JPA parallel: cache-aside is what `@Cacheable` + `@CacheEvict` (Spring
 * Cache over Redis/Caffeine) do for you declaratively; the stampede guard is
 * Caffeine's per-key `LoadingCache` lock, or `sync = true` on `@Cacheable`.
 * Doing it by hand here is how you understand what those annotations buy you.
 * ============================================================================
 */
describe('Kata 04 — Caching (e2e)', () => {
  let app: INestApplication;
  let redis: Redis;

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();
    app = moduleRef.createNestApplication();
    await app.init();
    redis = app.get<Redis>(REDIS);
  });

  afterAll(async () => {
    await app?.close();
  });

  /** Grab a real seeded product id (seed uses generated UUIDs). */
  const anyProductId = async (): Promise<string> => {
    const res = await request(app.getHttpServer())
      .get('/products?limit=5')
      .expect(200);
    expect(Array.isArray(res.body)).toBe(true);
    expect(res.body.length).toBeGreaterThan(0);
    return res.body[0].id;
  };

  it('first read is a MISS (source:"db"), the next is a HIT (source:"cache") with identical data', async () => {
    const id = await anyProductId();
    await redis.flushdb(); // guarantee the key is cold

    const miss = await request(app.getHttpServer())
      .get(`/products/${id}`)
      .expect(200);
    expect(miss.body.id).toBe(id);
    expect(miss.body.source).toBe('db');

    const hit = await request(app.getHttpServer())
      .get(`/products/${id}`)
      .expect(200);
    expect(hit.body.source).toBe('cache');
    // same payload, minus the source marker
    expect({ ...hit.body, source: undefined }).toEqual({
      ...miss.body,
      source: undefined,
    });
  });

  it('caches each id under its own key (no global-key collision)', async () => {
    const res = await request(app.getHttpServer())
      .get('/products?limit=5')
      .expect(200);
    const [a, b] = res.body;
    expect(a.id).not.toBe(b.id);
    await redis.flushdb();

    const missA = await request(app.getHttpServer())
      .get(`/products/${a.id}`)
      .expect(200);
    const missB = await request(app.getHttpServer())
      .get(`/products/${b.id}`)
      .expect(200);

    // b must be its OWN cold miss, not a wrongly-shared hit off a's entry
    expect(missA.body.id).toBe(a.id);
    expect(missB.body.id).toBe(b.id);
    expect(missB.body.source).toBe('db');

    const hitB = await request(app.getHttpServer())
      .get(`/products/${b.id}`)
      .expect(200);
    expect(hitB.body.id).toBe(b.id);
    expect(hitB.body.source).toBe('cache');
  });

  it('invalidates the cache on write: a purchase makes the next read fresh and correct', async () => {
    const id = await anyProductId();
    await redis.flushdb();

    // warm the cache
    const before = await request(app.getHttpServer())
      .get(`/products/${id}`)
      .expect(200);
    expect(before.body.source).toBe('db');
    const stockBefore = before.body.stock;
    expect(stockBefore).toBeGreaterThan(0);

    // confirm it is now cached
    await request(app.getHttpServer())
      .get(`/products/${id}`)
      .expect(200)
      .then((r) => expect(r.body.source).toBe('cache'));

    // mutate stock behind the cache's back
    await request(app.getHttpServer())
      .post(`/products/${id}/purchase`)
      .send({ quantity: 1 })
      .expect((r) => expect([200, 201]).toContain(r.status));

    // the cache MUST NOT serve the stale stock
    const after = await request(app.getHttpServer())
      .get(`/products/${id}`)
      .expect(200);
    expect(after.body.stock).toBe(stockBefore - 1);
    expect(after.body.source).toBe('db'); // invalidated, so this is a fresh read
  });

  it(
    'does NOT stampede: a burst of concurrent cold reads hits the DB exactly once',
    async () => {
      const id = await anyProductId();
      await redis.flushdb(); // cold key

      const start = await request(app.getHttpServer())
        .get(`/products/${id}/db-reads`)
        .expect(200);
      const before = start.body.dbReads;
      expect(typeof before).toBe('number');

      const burst = 20;
      const responses = await Promise.all(
        Array.from({ length: burst }, () =>
          request(app.getHttpServer()).get(`/products/${id}`),
        ),
      );

      responses.forEach((res) => {
        expect(res.status).toBe(200);
        expect(res.body.id).toBe(id);
      });

      const end = await request(app.getHttpServer())
        .get(`/products/${id}/db-reads`)
        .expect(200);
      // single-flight: the cold key was loaded from Postgres ONCE, not `burst` times
      expect(end.body.dbReads - before).toBe(1);
    },
    15000,
  );
});
