import { INestApplication } from '@nestjs/common'
import { Test } from '@nestjs/testing'
import request from 'supertest'
import { randomUUID } from 'node:crypto'
import Redis from 'ioredis'
import { AppModule } from '../../src/app.module'
import { REDIS } from '../../src/redis/redis.module'

/**
 * ============================================================================
 * KATA 06 — RATE LIMITING  (Week 6)   — per-user token bucket in Redis
 * ============================================================================
 * These tests are RED on a fresh `kata-06-rate-limiting` branch. Today there is
 * no `GET /limited` endpoint (404), and nothing counts requests per caller.
 * Your assignment: add a rate-limited endpoint that lets each user make at most
 * LIMIT requests per rolling window, then answers `429 Too Many Requests` with
 * a `Retry-After` header. The counter/bucket lives in Redis, and the check MUST
 * be atomic so a concurrent burst can never over-admit. Do NOT edit this file —
 * the spec is the contract.
 *
 * Run just this kata:
 *   npm run test:kata -- test/katas/kata-06-rate-limiting.e2e-spec.ts
 *
 * ---------------------------------------------------------------------------
 * CONTRACT
 * ---------------------------------------------------------------------------
 * GET /limited          header: `X-User-Id: <string>`  (the rate-limit subject)
 *   -> 200 { ok: true }              while the caller still has budget in the
 *                                    current window.
 *   -> 429 (Too Many Requests)       once the caller has spent LIMIT requests in
 *                                    the window. The 429 response MUST carry a
 *                                    `Retry-After` header: an integer number of
 *                                    seconds until budget frees up, in (0, WINDOW].
 *
 *   The limit is PER `X-User-Id`: one user exhausting their budget must not
 *   affect another user. Different users have independent buckets.
 *
 * Tunables the tests assume (state them as constants in your limiter so they
 * match this spec exactly):
 *   LIMIT           = 100 requests
 *   WINDOW_SECONDS  = 60
 *
 * ---------------------------------------------------------------------------
 * THE NASTY CASE — check-then-act race (over-admission under concurrency)
 * ---------------------------------------------------------------------------
 * The naive limiter is two round-trips: `n = GET key; if (n < LIMIT) INCR key`.
 * Fire LIMIT+overshoot requests concurrently and they ALL read a count below
 * LIMIT before anyone increments -> every request is admitted and the limit is
 * blown. This is the same check-then-act race as kata-02, now in Redis. The fix
 * is to make the decision and the state change ONE atomic step — a single
 * `INCR` (and reject when the returned value exceeds LIMIT), or a Lua script for
 * a real token bucket. Redis runs one command at a time, so one command = one
 * atomic decision. The last assertion pins admitted === LIMIT exactly across a
 * concurrent burst.
 *
 * Spring/JPA parallel: this is a servlet `Filter` / AOP `@Around` (or Bucket4j
 * over Redis) in Spring; in Nest the seam is a Guard (`CanActivate`) or an
 * interceptor that runs before the handler and rejects early. `@nestjs/throttler`
 * is the off-the-shelf version — you are hand-rolling it once to see the atomics.
 * ============================================================================
 */
describe('Kata 06 — Rate limiting (e2e)', () => {
  let app: INestApplication
  let redis: Redis

  const LIMIT = 100
  const WINDOW_SECONDS = 60

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [AppModule],
    }).compile()
    app = moduleRef.createNestApplication()
    // Must actually LISTEN (not just init): the concurrency test fires a burst
    // of supertest calls at app.getHttpServer(). Against an unbound server they
    // race to listen() on the same socket -> ECONNRESET. Binding once here makes
    // supertest reuse the live address. (Same fix as kata-02 / kata-04.)
    await app.listen(0)
    redis = app.get<Redis>(REDIS)
  })

  afterAll(async () => {
    await app?.close()
  })

  /** A brand-new user id => a fresh, full bucket, isolated from other tests. */
  const freshUser = (): string => `u-${randomUUID()}`

  const hit = (userId: string) =>
    request(app.getHttpServer()).get('/limited').set('X-User-Id', userId)

  it('allows a request while the user still has budget', async () => {
    const res = await hit(freshUser()).expect(200)
    expect(res.body.ok).toBe(true)
  })

  it('allows exactly LIMIT requests, then answers 429 with a valid Retry-After', async () => {
    const user = freshUser()

    // Spend the whole budget — every one of the first LIMIT requests is allowed.
    for (let i = 0; i < LIMIT; i++) {
      await hit(user).expect(200)
    }

    // The next request is over the limit.
    const blocked = await hit(user).expect(429)

    // Retry-After must be an integer number of seconds in (0, WINDOW].
    const retryAfter = Number(blocked.headers['retry-after'])

    expect(Number.isInteger(retryAfter)).toBe(true)
    expect(retryAfter).toBeGreaterThan(0)
    expect(retryAfter).toBeLessThanOrEqual(WINDOW_SECONDS)
  })

  it('is per-user: one user hitting the limit does not throttle another', async () => {
    const noisy = freshUser()
    const quiet = freshUser()

    // Exhaust the noisy user.
    for (let i = 0; i < LIMIT; i++) {
      await hit(noisy).expect(200)
    }
    await hit(noisy).expect(429)

    // The quiet user still has a full, independent bucket.
    const res = await hit(quiet).expect(200)
    expect(res.body.ok).toBe(true)
  })

  it('does NOT over-admit under a concurrent burst: exactly LIMIT succeed, the rest are 429', async () => {
    const user = freshUser()
    const overshoot = 25

    const responses = await Promise.all(
      Array.from({ length: LIMIT + overshoot }, () => hit(user)),
    )

    const allowed = responses.filter((r) => r.status === 200).length
    const throttled = responses.filter((r) => r.status === 429).length

    // Atomic check-and-decrement: never more than LIMIT get through, and no
    // request is lost to a third status code.
    expect(allowed).toBe(LIMIT)
    expect(throttled).toBe(overshoot)
  }, 20000)
})
