import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import { DataSource } from 'typeorm';
import request from 'supertest';
import { AppModule } from '../../src/app.module';

/**
 * ============================================================================
 * KATA 07 — QUERY PERFORMANCE  (Week 7)   — index a slow query + keyset paging
 * ============================================================================
 * These tests are RED on a fresh `kata-07-query-performance` branch. There is
 * no /events route yet, and the `events` table ships WITHOUT its performance
 * index. Your assignment is a user activity feed that stays fast and correct at
 * scale: the newest events for one user, cursor-paginated, served by an index
 * — no Seq Scan, no Sort, and no duplicated rows when new events arrive between
 * page fetches. Do NOT edit this file — the spec is the contract.
 *
 * Run just this kata:
 *   npm run test:kata -- test/katas/kata-07-query-performance.e2e-spec.ts
 *
 * ---------------------------------------------------------------------------
 * THE TWO FAILURE MODES THIS KATA DEFENDS AGAINST
 * ---------------------------------------------------------------------------
 * 1) THE SLOW QUERY. `SELECT ... WHERE user_id = $1 ORDER BY created_at DESC
 *    LIMIT n` over a big table with no matching index = a full Seq Scan to find
 *    the user's rows, then a Sort to order them, then throw all but n away. It
 *    looks instant on 100 rows and melts at 1M. The fix is a COVERING composite
 *    index whose column order matches the WHERE (equality) then the ORDER BY, so
 *    Postgres walks the index in order and stops after n — no scan, no sort.
 *
 * 2) OFFSET PAGING IS NOT STABLE. `... ORDER BY created_at DESC OFFSET 50 LIMIT
 *    50` assumes the rows below you never move. Insert ONE newer event between
 *    fetching page 1 and page 2 and every row shifts down by one — so page 2
 *    now re-serves the last row of page 1. Users see a duplicate; an importer
 *    paging to the end processes a row twice. KEYSET (cursor) paging remembers
 *    WHERE you were — "give me rows strictly older than (created_at,id)=X" — so
 *    inserts at the head never shift the window.
 *
 * Spring/JPA parallel: this is why `Pageable` with a plain `Page<T>` (LIMIT/
 * OFFSET) is a trap on hot, growing tables — Spring Data's own docs steer you to
 * keyset/`ScrollPosition` (`Window<T>`, `scrollByKeyset`) for exactly this. And
 * a composite `@Index(columnList = "userId, createdAt DESC")` in JPA is the same
 * lever as the migration you write here; `EXPLAIN` is how you PROVE the planner
 * actually took it instead of trusting that it did.
 * Docs: https://use-the-index-luke.com/no-offset
 *       https://www.postgresql.org/docs/current/using-explain.html
 *
 * ---------------------------------------------------------------------------
 * CONTRACT
 * ---------------------------------------------------------------------------
 * GET /events?userId=<int>&limit=<int>&cursor=<opaque?>
 *   -> 200 {
 *        items: Array<{ id, userId, createdAt, kind }>,   // NEWEST first
 *        nextCursor: string | null
 *      }
 *   Ordering: strictly by (created_at DESC, id DESC) — newest first, id as the
 *     tiebreaker so the order is total (never ambiguous under equal timestamps).
 *   Filter:   only rows for `userId`.
 *   limit:    how many rows to return (default is yours; these tests pass it).
 *   cursor:   OPAQUE. It comes from a previous response's `nextCursor`; the
 *     client passes it back verbatim. It must encode the position of the LAST
 *     row returned so the next page is the rows STRICTLY AFTER it in the
 *     ordering (keyset). It must NOT be a numeric OFFSET.
 *   nextCursor: the token to fetch the page after this one, or `null` when this
 *     page reached the end.
 *
 * REQUIRED (part of the contract, graded by EXPLAIN below):
 *   The feed query must be served by an INDEX SCAN with NO Seq Scan and NO Sort
 *   node. That forces a composite index on the `events` table whose leading
 *   column is `user_id` and whose remaining columns provide the `created_at`/
 *   `id` ordering. Add it in a NEW migration — the scaffold migration ships the
 *   table with its primary key only, on purpose.
 * ============================================================================
 */

// The user whose feed we grade. Seeded deterministically below; kept out of the
// noise user-id range so the planner sees a selective, index-friendly filter.
const FEED_USER = 900001;
const TARGET_ROWS = 2000; // this user's events
const NOISE_ROWS = 60000; // other users' events, so the table is big & the filter selective
const PAGE = 50;

type FeedItem = { id: string | number; userId: number; createdAt: string; kind: string };

describe('Kata 07 — Query performance (e2e)', () => {
  let app: INestApplication;
  let dataSource: DataSource;

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();
    app = moduleRef.createNestApplication();
    await app.init();
    dataSource = app.get(DataSource);

    // --- Test-side seeding only (NOT the src/ you write). ---------------------
    // If this throws `relation "events" does not exist`, run your CreateEvents
    // migration first (on Codespace). Bulk-insert via generate_series so even
    // 60k rows is one fast round trip, then ANALYZE so the planner has real
    // stats to choose the index (without stats it guesses and EXPLAIN is a lie).
    await dataSource.query('TRUNCATE TABLE events RESTART IDENTITY');
    // Noise: many users, so FEED_USER is a small, selective slice of a big table.
    await dataSource.query(
      `INSERT INTO events (user_id, created_at, kind)
       SELECT (g % 2000) + 1, now() - (g || ' seconds')::interval, 'noise'
       FROM generate_series(1, $1) g`,
      [NOISE_ROWS],
    );
    // Target user: created_at strictly increasing with g, so g is exactly the
    // newest-first rank (g=TARGET_ROWS is the freshest). Inserted after the
    // noise, so ids ascend with g too — (created_at, id) agree, ordering is total.
    await dataSource.query(
      `INSERT INTO events (user_id, created_at, kind)
       SELECT $1, timestamptz '2020-01-01 00:00:00+00' + (g || ' seconds')::interval, 'target'
       FROM generate_series(1, $2) g`,
      [FEED_USER, TARGET_ROWS],
    );
    await dataSource.query('ANALYZE events');
  }, 60000);

  afterAll(async () => {
    await app?.close();
  });

  const getFeed = async (
    query: Record<string, string | number>,
  ): Promise<{ items: FeedItem[]; nextCursor: string | null }> => {
    const res = await request(app.getHttpServer()).get('/events').query(query).expect(200);
    return res.body;
  };

  const idsOf = (items: FeedItem[]): string[] => items.map((i) => String(i.id));
  const isStrictlyDescendingByCreatedAt = (items: FeedItem[]): boolean =>
    items.every(
      (row, i) =>
        i === 0 ||
        new Date(items[i - 1].createdAt).getTime() > new Date(row.createdAt).getTime(),
    );

  it('returns a correct, newest-first first page filtered to one user', async () => {
    const page = await getFeed({ userId: FEED_USER, limit: PAGE });

    expect(page.items).toHaveLength(PAGE);
    // every row belongs to the requested user — no noise leaks in
    expect(page.items.every((r) => Number(r.userId) === FEED_USER)).toBe(true);
    // newest first, strictly ordered
    expect(isStrictlyDescendingByCreatedAt(page.items)).toBe(true);
    // the very first row is genuinely the freshest event for this user
    const [{ max }] = await dataSource.query(
      'SELECT max(created_at) AS max FROM events WHERE user_id = $1',
      [FEED_USER],
    );
    expect(new Date(page.items[0].createdAt).getTime()).toBe(new Date(max).getTime());
    // there is more to fetch, so we get a cursor to continue
    expect(typeof page.nextCursor).toBe('string');
    expect((page.nextCursor as string).length).toBeGreaterThan(0);
  });

  it('advances by cursor to the next page with no overlap and no gap', async () => {
    const p1 = await getFeed({ userId: FEED_USER, limit: PAGE });
    const p2 = await getFeed({ userId: FEED_USER, limit: PAGE, cursor: p1.nextCursor as string });

    expect(p2.items).toHaveLength(PAGE);
    // disjoint: page 2 must not repeat any row from page 1
    const p1ids = new Set(idsOf(p1.items));
    expect(idsOf(p2.items).some((id) => p1ids.has(id))).toBe(false);
    // contiguous: page 2 starts strictly OLDER than page 1 ended (no gap, no jump back)
    const p1Last = new Date(p1.items[p1.items.length - 1].createdAt).getTime();
    const p2First = new Date(p2.items[0].createdAt).getTime();
    expect(p2First).toBeLessThan(p1Last);
    // the two pages together are one clean descending run
    expect(isStrictlyDescendingByCreatedAt([...p1.items, ...p2.items])).toBe(true);
  });

  it('keyset paging is STABLE when a newer event is inserted between pages (OFFSET would duplicate)', async () => {
    const p1 = await getFeed({ userId: FEED_USER, limit: PAGE });
    const p1ids = new Set(idsOf(p1.items));

    // A brand-new NEWEST event lands for this user AFTER page 1 was fetched but
    // BEFORE page 2. Under OFFSET 50/LIMIT 50 this shoves every row down one, so
    // page 2 re-serves p1's last row. Under keyset paging the cursor is anchored
    // to a row's position, so the new head is simply out of page 2's range.
    const [{ id: newHeadId }] = await dataSource.query(
      `INSERT INTO events (user_id, created_at, kind)
       VALUES ($1, timestamptz '2020-01-01 00:00:00+00' + '3000 seconds'::interval, 'target-new')
       RETURNING id`,
      [FEED_USER],
    );

    const p2 = await getFeed({ userId: FEED_USER, limit: PAGE, cursor: p1.nextCursor as string });

    // the newly inserted head is newer than the cursor -> it belongs BEFORE the
    // cursor, so it must NOT appear on page 2
    expect(idsOf(p2.items)).not.toContain(String(newHeadId));
    // and — the whole point — no page-1 row is duplicated onto page 2
    expect(idsOf(p2.items).some((id) => p1ids.has(id))).toBe(false);
    // page 2 is still the correct next slice
    expect(p2.items).toHaveLength(PAGE);
    const p1Last = new Date(p1.items[p1.items.length - 1].createdAt).getTime();
    expect(new Date(p2.items[0].createdAt).getTime()).toBeLessThan(p1Last);
  });

  it('serves the feed query from an INDEX — no Seq Scan, no Sort (EXPLAIN)', async () => {
    // Grade the physical plan of the canonical feed query directly. With the
    // right composite index the planner walks it in order and stops after LIMIT:
    // an Index Scan, no Sort. Without it: Seq Scan + Sort. (This checks the index
    // exists and is usable; the HTTP tests above check you actually query this way.)
    const explained = await dataSource.query(
      `EXPLAIN (FORMAT JSON)
       SELECT id, user_id, created_at, kind
       FROM events
       WHERE user_id = $1
       ORDER BY created_at DESC, id DESC
       LIMIT $2`,
      [FEED_USER, PAGE],
    );

    // pg returns [{ 'QUERY PLAN': [ { Plan: {...} } ] }]
    const rootPlan = explained[0]['QUERY PLAN'][0].Plan;
    const nodeTypes: string[] = [];
    const walk = (node: any) => {
      if (!node) return;
      nodeTypes.push(node['Node Type']);
      (node.Plans ?? []).forEach(walk);
    };
    walk(rootPlan);

    const hasIndexScan = nodeTypes.some((t) => t === 'Index Scan' || t === 'Index Only Scan');
    const hasSeqScan = nodeTypes.includes('Seq Scan');
    const hasSort = nodeTypes.includes('Sort');

    expect(hasSeqScan).toBe(false); // an unindexed filter scans the whole table
    expect(hasSort).toBe(false); // a non-covering index still forces a Sort
    expect(hasIndexScan).toBe(true); // ordering comes from the index itself
  });
});
