import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { randomUUID } from 'crypto';
import { AppModule } from '../../src/app.module';

/**
 * ============================================================================
 * KATA 01 — IDEMPOTENCY  (Week 1)
 * ============================================================================
 * These tests are RED on a fresh `seed` branch (there is no /orders endpoint
 * yet). Your assignment is to make them GREEN by implementing an idempotent
 * `POST /orders` in `src/`. Do NOT edit this file — the spec is the contract.
 *
 * Run just this kata:
 *   npm run test:kata -- test/katas/kata-01-idempotency.e2e-spec.ts
 *
 * Contract:
 *   POST /orders
 *     headers: { "Idempotency-Key": "<client-supplied unique key>" }
 *     body:    { "productId": "<uuid>", "quantity": <positive int> }
 *   -> 201 Created  body: { id, productId, quantity }
 *   Replay same key -> returns the SAME order id (no duplicate row created).
 *   Different key   -> a new, different order id.
 *   Missing key     -> 400 Bad Request.
 *
 * The real lesson lives in the replay case: where do you store the key, and how
 * do you avoid a race when two identical requests arrive at once? (Spring
 * parallel: this is the same problem an @Transactional + unique-constraint or a
 * dedicated idempotency store solves in your day job.)
 * ============================================================================
 */
describe('Kata 01 — Idempotency (e2e)', () => {
  let app: INestApplication;

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();
    app = moduleRef.createNestApplication();
    await app.init();
  });

  afterAll(async () => {
    await app?.close();
  });

  const orderBody = () => ({
    productId: '00000000-0000-0000-0000-000000000001',
    quantity: 1,
  });

  it('creates an order when given an Idempotency-Key', async () => {
    const res = await request(app.getHttpServer())
      .post('/orders')
      .set('Idempotency-Key', randomUUID())
      .send(orderBody())
      .expect(201);
    expect(res.body.id).toBeDefined();
  });

  it('returns the SAME order when the key is replayed', async () => {
    const key = randomUUID();
    const first = await request(app.getHttpServer())
      .post('/orders')
      .set('Idempotency-Key', key)
      .send(orderBody());
    const second = await request(app.getHttpServer())
      .post('/orders')
      .set('Idempotency-Key', key)
      .send(orderBody());
    expect(first.body.id).toBeDefined();
    expect(second.body.id).toBe(first.body.id);
  });

  it('creates DIFFERENT orders for different keys', async () => {
    const a = await request(app.getHttpServer())
      .post('/orders')
      .set('Idempotency-Key', randomUUID())
      .send(orderBody());
    const b = await request(app.getHttpServer())
      .post('/orders')
      .set('Idempotency-Key', randomUUID())
      .send(orderBody());
    expect(a.body.id).not.toBe(b.body.id);
  });

  it('rejects a request with no Idempotency-Key', async () => {
    await request(app.getHttpServer())
      .post('/orders')
      .send(orderBody())
      .expect(400);
  });
});
