import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { randomUUID } from 'crypto';
import { DataSource } from 'typeorm';
import { AppModule } from '../../src/app.module';
import { Account } from '../../src/accounts/account.entity';

/**
 * ============================================================================
 * KATA 03 — TRANSACTIONS & CONSISTENCY  (Week 3)
 * ============================================================================
 * These tests are RED on a fresh `kata-03` branch (there is no transfer
 * endpoint yet). Your assignment is to make them GREEN by implementing a money
 * transfer between two accounts that moves BOTH rows atomically — both change
 * or neither. Do NOT edit this file — the spec is the contract.
 *
 * Run just this kata:
 *   npm run test:kata -- test/katas/kata-03-transactions.e2e-spec.ts
 *
 * Contract:
 *   POST /accounts/:id/transfer          (:id is the SOURCE account)
 *     body: { "toAccountId": "<uuid>", "amountCents": <positive int> }
 *   -> 200/201  body: { fromAccountId, toAccountId, amountCents,
 *                       fromBalanceCents, toBalanceCents }
 *              (source debited AND destination credited by amountCents)
 *   -> 409 Conflict   when the source has insufficient funds
 *                     (BOTH balances UNCHANGED — a clean no-op)
 *   -> 404 Not Found  when the destination account does not exist
 *                     (source balance UNCHANGED — no money debited into the void)
 *
 * The lesson: a transfer is TWO writes — debit the source, credit the
 * destination. Done naively they are two independent statements:
 *
 *     source.balance -= amount;  save(source);   // committed
 *     dest.balance   += amount;  save(dest);     // …what if THIS throws?
 *
 * If anything fails between them (dest doesn't exist, the process crashes, the
 * DB drops the connection), the source is already debited and the money has
 * VANISHED. The invariant that must hold no matter what: the total money across
 * the two accounts is conserved — no statement creates or destroys value. That
 * only holds if both writes commit together or not at all.
 *
 * The nasty case (the one that grades you):
 *   (1) Transfer into a non-existent destination — a naive debit-then-credit
 *       leaks the source's money; a transactional one leaves the source whole.
 *   (2) Under concurrency: seed A=1000, B=0, fire 20 transfers of 100 A->B at
 *       once. EXACTLY 10 may succeed; A+B must ALWAYS equal 1000 (money is
 *       neither created nor destroyed); no balance may go negative.
 *
 * Spring/JPA parallel: this is @Transactional wrapping the debit + credit in one
 * unit of work (TypeORM `dataSource.transaction()` / a `QueryRunner`). Combine it
 * with the Week-2 locking you already know — the transaction gives you
 * all-or-nothing; the lock (FOR UPDATE / @Version / a conditional UPDATE) keeps
 * two concurrent transfers from losing each other's update on the shared rows.
 * ============================================================================
 */
describe('Kata 03 — Transactions & consistency (e2e)', () => {
  let app: INestApplication;
  let dataSource: DataSource;
  // Bind a real port (see kata-02): firing concurrent supertest calls at an
  // unbound getHttpServer() races on listen() and resets connections, hiding the
  // real result. A bound port is the honest way to test money under load.
  let base: string;

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();
    app = moduleRef.createNestApplication();
    await app.listen(0);
    dataSource = app.get(DataSource);
    base = (await app.getUrl()).replace('[::1]', '127.0.0.1');
    // Warm the pool so the graded burst races on already-open connections (a
    // cold pool serializes the first burst and can hide a lost-update bug).
    await Promise.all(
      Array.from({ length: 30 }, () => request(base).get('/health')),
    );
  });

  afterAll(async () => {
    await app?.close();
  });

  // Test-side setup only — NOT part of the src/ you must write.
  const seedAccount = async (balanceCents: number): Promise<string> => {
    const repo = dataSource.getRepository(Account);
    const saved = await repo.save(
      repo.create({
        name: `kata03-${Date.now()}-${Math.random()}`,
        balanceCents,
      }),
    );
    return saved.id;
  };

  const balanceOf = async (id: string): Promise<number> => {
    const a = await dataSource.getRepository(Account).findOneBy({ id });
    return a!.balanceCents;
  };

  it('moves money from source to destination on a valid transfer', async () => {
    const from = await seedAccount(1000);
    const to = await seedAccount(0);

    const res = await request(base)
      .post(`/accounts/${from}/transfer`)
      .send({ toAccountId: to, amountCents: 300 });

    expect([200, 201]).toContain(res.status);
    expect(await balanceOf(from)).toBe(700);
    expect(await balanceOf(to)).toBe(300);
  });

  it('rejects an over-balance transfer with 409, leaving BOTH balances untouched', async () => {
    const from = await seedAccount(100);
    const to = await seedAccount(0);

    await request(base)
      .post(`/accounts/${from}/transfer`)
      .send({ toAccountId: to, amountCents: 500 })
      .expect(409);

    expect(await balanceOf(from)).toBe(100);
    expect(await balanceOf(to)).toBe(0);
  });

  it('does not debit the source when the destination does not exist (nothing partially committed)', async () => {
    const from = await seedAccount(1000);
    const to = await seedAccount(0);

    // Control: one valid transfer proves the endpoint is live and actually moves
    // money. After this the source holds 900 — that's our known-good baseline.
    const control = await request(base)
      .post(`/accounts/${from}/transfer`)
      .send({ toAccountId: to, amountCents: 100 });
    expect([200, 201]).toContain(control.status);

    // Now transfer into a non-existent destination. The credit MUST fail; the
    // invariant that grades you is that the source's debit rolled back with it —
    // a naive debit-then-credit leaves the source at 700 (money vanished).
    const res = await request(base)
      .post(`/accounts/${from}/transfer`)
      .send({ toAccountId: randomUUID(), amountCents: 200 });

    expect(res.status).toBeGreaterThanOrEqual(400);
    expect(await balanceOf(from)).toBe(900);
  });

  it(
    'conserves money under 20 concurrent transfers — exactly 10 succeed, A+B always 1000, never negative',
    async () => {
      const attempts = 20;
      const amount = 100;

      // Several fresh rounds: a single burst can get lucky on a quiet pool; a
      // lost update or a torn debit/credit breaks the invariant on at least one.
      for (let round = 0; round < 4; round++) {
        const from = await seedAccount(1000);
        const to = await seedAccount(0);

        const responses = await Promise.all(
          Array.from({ length: attempts }, () =>
            request(base)
              .post(`/accounts/${from}/transfer`)
              .send({ toAccountId: to, amountCents: amount }),
          ),
        );

        const ok = responses.filter((r) => r.status === 200 || r.status === 201);
        const conflict = responses.filter((r) => r.status === 409);

        // Every response is a clean outcome — no 500s, no dropped requests.
        expect(ok.length + conflict.length).toBe(attempts);
        // 1000 / 100 = exactly 10 transfers fit; the other 10 hit 409.
        expect(ok.length).toBe(10);
        expect(conflict.length).toBe(attempts - 10);

        const fromBal = await balanceOf(from);
        const toBal = await balanceOf(to);
        // The invariant that matters: money is conserved and never goes negative.
        expect(fromBal).toBeGreaterThanOrEqual(0);
        expect(fromBal + toBal).toBe(1000);
        expect(fromBal).toBe(0);
        expect(toBal).toBe(1000);
      }
    },
    30000,
  );
});
