import { INestApplication } from '@nestjs/common'
import { Test } from '@nestjs/testing'
import request from 'supertest'
import { AppModule } from '../../src/app.module'

/**
 * ============================================================================
 * KATA 08 — OBSERVABILITY  (Week 8)   — trace-id end-to-end + latency metric
 * ============================================================================
 * These tests are RED on a fresh `kata-08-observability` branch. There is no
 * /observe route yet. Your assignment: give every request a TRACE-ID, carry
 * that same id THROUGH a queue job into the worker (a separate loop that shares
 * nothing with the request but Redis), and record a LATENCY METRIC per request.
 * Do NOT edit this file — the spec is the contract.
 *
 * Run just this kata:
 *   npm run test:kata -- test/katas/kata-08-observability.e2e-spec.ts
 *
 * ---------------------------------------------------------------------------
 * WHY THIS IS THE HARD ONE
 * ---------------------------------------------------------------------------
 * A trace-id is trivial to attach to ONE request. The failure mode this kata
 * defends against is the id VANISHING at an async boundary. Node's
 * AsyncLocalStorage (ALS) carries per-request context down the call stack of
 * THE SAME request — but a BullMQ worker runs in its own loop, picked up later,
 * with no ALS context at all. So the id only survives the queue hop if you put
 * it IN THE JOB PAYLOAD and re-establish context inside the processor. Reading
 * it back proves the whole chain held.
 *
 * Spring/JPA parallel: this is MDC (Mapped Diagnostic Context) + a Micrometer
 * Timer. MDC is thread-local, so it does NOT cross into an `@Async` thread pool
 * on its own — you need a `TaskDecorator` to copy MDC onto the worker thread,
 * exactly the copy-onto-the-job move you make here. The latency metric is a
 * Micrometer `Timer`/`@Timed` around the handler.
 * Docs: https://nodejs.org/api/async_context.html   (AsyncLocalStorage)
 *       https://docs.nestjs.com/interceptors        (timing interceptor)
 *
 * ---------------------------------------------------------------------------
 * CONTRACT
 * ---------------------------------------------------------------------------
 * Trace-id header name (in AND out): `X-Request-Id`.
 *
 * GET /observe/ping
 *   -> 200 { traceId: string }
 *      - If the request sends `X-Request-Id`, traceId ECHOES that exact value.
 *      - If it does not, the server GENERATES a non-empty id.
 *      - The response MUST also carry the trace-id in the `X-Request-Id` header,
 *        equal to body.traceId.
 *      - Two requests with no inbound id get DIFFERENT ids (per-request context,
 *        not one shared/global variable that leaks between requests).
 *
 * POST /observe/jobs
 *   body: { "workMs"?: number }   (default 0 — how long the worker "works")
 *   -> 202 { jobId: string }
 *      The handler ONLY enqueues. It MUST capture the CURRENT request's trace-id
 *      and hand it to the job so the worker can run under the same id.
 *
 * GET /observe/jobs/:jobId
 *   -> 200 { state: string, traceId: string | null }
 *      state    the BullMQ job state via job.getState(); "unknown" if not found.
 *      traceId  the trace-id the WORKER saw while processing this job. It MUST
 *               equal the trace-id of the POST request that created it. null
 *               until the worker has recorded it.
 *
 * GET /observe/metrics
 *   -> 200 { count: number, sumMs: number }
 *      count   how many /observe requests have been observed (a running total).
 *      sumMs   total measured handler latency in milliseconds across them.
 *      Each request must record its own duration; both numbers only grow.
 * ============================================================================
 */
describe('Kata 08 — Observability (e2e)', () => {
  let app: INestApplication

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [AppModule],
    }).compile()
    app = moduleRef.createNestApplication()
    await app.init()
  })

  afterAll(async () => {
    await app?.close()
  })

  /** Poll GET /observe/jobs/:jobId until state is terminal, or time out. */
  const waitForJob = async (
    jobId: string,
    terminal: string[],
    timeoutMs = 15000,
  ): Promise<{ state: string; traceId: string | null }> => {
    const deadline = Date.now() + timeoutMs
    let last = { state: 'unknown', traceId: null as string | null }
    while (Date.now() < deadline) {
      const res = await request(app.getHttpServer()).get(`/observe/jobs/${jobId}`)
      if (res.status === 200) {
        last = { state: res.body.state, traceId: res.body.traceId ?? null }
        if (terminal.includes(last.state)) return last
      }
      await new Promise((r) => setTimeout(r, 100))
    }
    return last
  }

  it('ATTACHES a trace-id: echoes an inbound X-Request-Id, sets it on the response header', async () => {
    const res = await request(app.getHttpServer())
      .get('/observe/ping')
      .set('X-Request-Id', 'trace-abc-123')
      .expect(200)

    expect(res.body.traceId).toBe('trace-abc-123')
    // the id also leaves on the response header, so a caller can correlate
    expect(res.headers['x-request-id']).toBe('trace-abc-123')
  })

  it('GENERATES a distinct id per request when none is supplied (no shared/global leak)', async () => {
    const a = await request(app.getHttpServer()).get('/observe/ping').expect(200)
    const b = await request(app.getHttpServer()).get('/observe/ping').expect(200)

    expect(typeof a.body.traceId).toBe('string')
    expect(a.body.traceId.length).toBeGreaterThan(0)
    // each request owns its own context — the id must not be one leaked global
    expect(a.body.traceId).not.toBe(b.body.traceId)
  })

  it('CARRIES the trace-id THROUGH the queue job into the worker (the nasty case)', async () => {
    // The worker is a separate loop with no request context — the id survives
    // only if it rode along inside the job payload.
    const enqueued = await request(app.getHttpServer())
      .post('/observe/jobs')
      .set('X-Request-Id', 'trace-xyz-789')
      .send({ workMs: 200 })
      .expect(202)

    const jobId = enqueued.body.jobId
    expect(typeof jobId).toBe('string')
    expect(jobId.length).toBeGreaterThan(0)

    const final = await waitForJob(jobId, ['completed', 'failed'])
    expect(final.state).toBe('completed')
    // end-to-end: the id the worker logged equals the id of the originating request
    expect(final.traceId).toBe('trace-xyz-789')
  }, 20000)

  it('CARRIES a GENERATED trace-id into the worker (one id per request, not two)', async () => {
    // No inbound X-Request-Id: the server generates ONE id for this request.
    // The id on the response header and the id the worker saw must be that same
    // id — a second id minted inside the handler breaks the chain.
    const enqueued = await request(app.getHttpServer())
      .post('/observe/jobs')
      .send({ workMs: 0 })
      .expect(202)

    const headerId = enqueued.headers['x-request-id']
    expect(typeof headerId).toBe('string')
    expect(headerId.length).toBeGreaterThan(0)

    const final = await waitForJob(enqueued.body.jobId, ['completed', 'failed'])
    expect(final.state).toBe('completed')
    expect(final.traceId).toBe(headerId)
  }, 20000)

  it('RECORDS a latency metric for each request (count and duration only grow)', async () => {
    const before = await request(app.getHttpServer())
      .get('/observe/metrics')
      .expect(200)

    await request(app.getHttpServer()).get('/observe/ping').expect(200)

    const after = await request(app.getHttpServer())
      .get('/observe/metrics')
      .expect(200)

    expect(typeof after.body.count).toBe('number')
    expect(typeof after.body.sumMs).toBe('number')
    // the extra ping was measured: the running totals moved up
    expect(after.body.count).toBeGreaterThan(before.body.count)
    expect(after.body.sumMs).toBeGreaterThan(0)
  })
})
