import { INestApplication } from '@nestjs/common';
import { Test } from '@nestjs/testing';
import request from 'supertest';
import { DataSource } from 'typeorm';
import { AppModule } from '../../src/app.module';
import { Product } from '../../src/products/product.entity';

/**
 * ============================================================================
 * KATA 02 — CONCURRENCY & LOCKING  (Week 2)
 * ============================================================================
 * These tests are RED on a fresh `kata-02` branch (there is no purchase
 * endpoint yet). Your assignment is to make them GREEN by implementing a
 * stock-decrementing purchase in `src/` that CANNOT oversell under load.
 * Do NOT edit this file — the spec is the contract.
 *
 * Run just this kata:
 *   npm run test:kata -- test/katas/kata-02-concurrency-locking.e2e-spec.ts
 *
 * Contract:
 *   POST /products/:id/purchase
 *     body: { "quantity": <positive int> }
 *   -> 200/201  body: { productId, quantity, remainingStock }   (stock decremented)
 *   -> 409 Conflict            when there is not enough stock (stock UNCHANGED)
 *
 * The lesson: a naive "read stock -> if enough, save(stock - qty)" is a
 * read-modify-write race. Two requests both read stock=1, both decide "yes",
 * both write 0 -> you sold 2 units of 1. This is a lost update. The whole point
 * of Week 2 is to make the decrement atomic under concurrency.
 *
 * The nasty case (the one that grades you): seed stock = 1, fire 50 buys at
 * once via Promise.all. EXACTLY ONE may succeed; the other 49 must get 409;
 * final stock must be 0 and NEVER negative. No 500s, no oversell.
 *
 * Spring/JPA parallel: this is @Version optimistic locking (TypeORM
 * @VersionColumn, already on Product) vs. SELECT ... FOR UPDATE pessimistic
 * locking (TypeORM `.setLock('pessimistic_write')`). Either can win this kata —
 * knowing WHEN you'd pick each is the day-job payoff. A conditional UPDATE
 * (`... SET stock = stock - :q WHERE id = :id AND stock >= :q`) is a third,
 * lock-free way to make the same guarantee at the DB.
 * ============================================================================
 */
describe('Kata 02 — Concurrency & locking (e2e)', () => {
  let app: INestApplication;
  let dataSource: DataSource;
  // Bind to a REAL ephemeral port and address requests by URL. Firing 50
  // concurrent supertest calls at app.getHttpServer() makes supertest race to
  // listen() on the same unbound server, which resets connections (ECONNRESET)
  // and hides the actual result. A bound port is the honest way to test load.
  let base: string;

  beforeAll(async () => {
    const moduleRef = await Test.createTestingModule({
      imports: [AppModule],
    }).compile();
    app = moduleRef.createNestApplication();
    await app.listen(0);
    dataSource = app.get(DataSource);
    base = (await app.getUrl()).replace('[::1]', '127.0.0.1');
    // Warm the DB connection pool. A COLD pool serializes the first burst of
    // concurrent requests (connections open one at a time), which accidentally
    // hides a lost-update bug — the read-modify-write only races once several
    // connections are live. Firing a batch of reads up front opens the pool so
    // every graded burst below races on already-open connections, the way a
    // server already under load would.
    await Promise.all(
      Array.from({ length: 30 }, () => request(base).get('/products')),
    );
  });

  afterAll(async () => {
    await app?.close();
  });

  // Seed a fresh product with a known starting stock. Returns its id so each
  // test is isolated from the others. (Test-side setup only — not part of the
  // src/ you must write.)
  const seedProduct = async (stock: number): Promise<string> => {
    const repo = dataSource.getRepository(Product);
    const saved = await repo.save(
      repo.create({ name: `kata02-${Date.now()}-${Math.random()}`, priceCents: 999, stock }),
    );
    return saved.id;
  };

  const stockOf = async (id: string): Promise<number> => {
    const p = await dataSource.getRepository(Product).findOneBy({ id });
    return p!.stock;
  };

  it('decrements stock on a successful purchase', async () => {
    const id = await seedProduct(10);
    const res = await request(base)
      .post(`/products/${id}/purchase`)
      .send({ quantity: 3 });
    expect([200, 201]).toContain(res.status);
    expect(await stockOf(id)).toBe(7);
  });

  it('rejects a purchase that exceeds available stock with 409, leaving stock untouched', async () => {
    const id = await seedProduct(1);
    await request(base)
      .post(`/products/${id}/purchase`)
      .send({ quantity: 2 })
      .expect(409);
    expect(await stockOf(id)).toBe(1);
  });

  it(
    'sells the LAST unit exactly once under 50 concurrent buys — no oversell',
    async () => {
      const attempts = 50;
      // Run the last-unit scenario several times on FRESH stock. A single burst
      // can get lucky (a cold/quiet pool serializes it and a lost-update bug
      // hides); correct locking holds the invariant on every burst, a race
      // breaks it on at least one. Every round must be clean.
      for (let round = 0; round < 4; round++) {
        const id = await seedProduct(1);

        const responses = await Promise.all(
          Array.from({ length: attempts }, () =>
            request(base)
              .post(`/products/${id}/purchase`)
              .send({ quantity: 1 }),
          ),
        );

        const ok = responses.filter((r) => r.status === 200 || r.status === 201);
        const conflict = responses.filter((r) => r.status === 409);

        // Every response is a clean outcome — no 500s, no dropped requests.
        expect(ok.length + conflict.length).toBe(attempts);
        // Exactly one buyer got the last unit.
        expect(ok.length).toBe(1);
        // The other 49 were told there was nothing left.
        expect(conflict.length).toBe(attempts - 1);
        // The invariant that matters: stock landed on 0 and never went negative.
        expect(await stockOf(id)).toBe(0);
      }
    },
    30000,
  );

  it(
    'sells exactly the available units under contention (stock=5, 30 concurrent buys)',
    async () => {
      const id = await seedProduct(5);
      const attempts = 30;

      const responses = await Promise.all(
        Array.from({ length: attempts }, () =>
          request(base)
            .post(`/products/${id}/purchase`)
            .send({ quantity: 1 }),
        ),
      );

      const ok = responses.filter((r) => r.status === 200 || r.status === 201);
      expect(ok.length).toBe(5);
      expect(await stockOf(id)).toBe(0);
    },
    20000,
  );
});
